#server
server:
  port: 10000

#log4jdbc
log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelgator

#datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_web?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
#    password: 202145105

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update

    #jpa format
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    database: mysql

  #log
  output:
    ansi:
      enabled: always